# config.yaml
app:
  name: "Regulatory Document Search System"
  version: "1.0.0"
  description: "AI-powered regulatory document search with Claude"

authentication:
  enable: true
  default_password: "regulatory2024"

claude:
  model: "claude-3-haiku-20240307"
  max_tokens: 4000
  temperature: 0.1

embeddings:
  model: "all-MiniLM-L6-v2"
  chunk_size: 1000
  chunk_overlap: 200

search:
  max_results: 10
  similarity_threshold: 0.3